name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Export environment variables
        run: |
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "ACCOUNT_ID=${{ secrets.ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "RAZOR_PAY_KEY=${{ secrets.RAZOR_PAY_KEY }}" >> $GITHUB_ENV
          echo "RAZOR_PAY_SECRET=${{ secrets.RAZOR_PAY_SECRET }}" >> $GITHUB_ENV

      - name: Install Terraform
        run: |
          curl -fsSL https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip -o terraform.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      - name: Install Terragrunt
        run: |
          curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.67.8/terragrunt_linux_amd64 -o terragrunt
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/
          terragrunt -version

      - name: Terragrunt Destroy
        working-directory: infrastructure/prod
        run: |
          terragrunt run-all init
          terragrunt run-all apply --terragrunt-non-interactive -auto-approve
          terragrunt run-all destroy --terragrunt-non-interactive -auto-approve
